import type { NextPage } from "next";
import Head from "next/head";
import Board from "src/Layout/Board";
import classes from "src/styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={classes.container}>
      <Head>
        <title>Tic Tac Toe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.main}>
        <Board />
      </main>
    </div>
  );
};

export default Home;
